import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const [template, styles, core, app] = await Promise.all([
  readFile(join(root, 'src/template.html'), 'utf8'),
  readFile(join(root, 'src/styles.css'), 'utf8'),
  readFile(join(root, 'src/qr-core.js'), 'utf8'),
  readFile(join(root, 'src/app.js'), 'utf8'),
]);

const safeScript = (source) => source.replace(/<\/script/gi, '<\\/script');
let html = template
  .replace('/*__STYLES__*/', () => styles.trim())
  .replace('/*__QR_CORE__*/', () => safeScript(core.trim()))
  .replace('/*__APP__*/', () => safeScript(app.trim()));

if (/\/\*__(STYLES|QR_CORE|APP)__\*\//.test(html)) {
  throw new Error('Build failed: unresolved template placeholder.');
}
html = `<!-- Generated by npm run build. Edit files under src/, not this file. -->\n${html.trim()}\n`;
await writeFile(join(root, 'index.html'), html, 'utf8');
console.log(`Built index.html (${Buffer.byteLength(html).toLocaleString()} bytes)`);
