import { readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const files = ['src/template.html', 'src/styles.css', 'src/qr-core.js', 'src/app.js', 'index.html'];
const contents = Object.fromEntries(await Promise.all(files.map(async (file) => [file, await readFile(join(root, file), 'utf8')])));
const errors = [];
const fail = (message) => errors.push(message);

for (const [file, text] of Object.entries(contents)) {
  if (/\t/.test(text)) fail(`${file}: tabs are not allowed`);
  if (/\r/.test(text)) fail(`${file}: CRLF line endings found`);
  if (/ +$/m.test(text)) fail(`${file}: trailing whitespace found`);
}

const app = contents['src/app.js'];
for (const forbidden of ['fetch(', 'XMLHttpRequest', 'WebSocket(', 'EventSource(', 'sendBeacon(']) {
  if (app.includes(forbidden)) fail(`src/app.js: network primitive found: ${forbidden}`);
}
const template = contents['src/template.html'];
if (!template.includes("connect-src 'none'")) fail('src/template.html: restrictive CSP connect-src is missing');
if (!template.includes('no-referrer')) fail('src/template.html: no-referrer policy is missing');
if (!template.includes('aria-live')) fail('src/template.html: live status region is missing');
if (!template.includes('<main')) fail('src/template.html: main landmark is missing');
if (!contents['index.html'].startsWith('<!-- Generated by npm run build.')) fail('index.html: generated-file banner is missing');
if (/\/\*__(STYLES|QR_CORE|APP)__\*\//.test(contents['index.html'])) fail('index.html: unresolved build placeholder');
const inlineScript = contents['index.html'].match(/<script>([\s\S]*?)<\/script>/i)?.[1];
if (!inlineScript) fail('index.html: inline application script is missing');
else {
  try { new vm.Script(inlineScript, { filename: 'index-inline.js' }); }
  catch (error) { fail(`index.html: generated inline JavaScript does not parse: ${error.message}`); }
}

if (errors.length) {
  console.error(errors.map((item) => `✗ ${item}`).join('\n'));
  process.exit(1);
}
console.log(`✓ Repository lint passed (${files.length} files checked)`);
